services:
  lol-tracker:
    build:
      context: ..
      dockerfile: lol-tracker/Dockerfile

    container_name: lol-tracker

    restart: unless-stopped

    env_file:
      - ../.env

    environment:
      LOL_DB_PATH: /data/lol.db

    volumes:
      - lol_tracker_data:/data

volumes:
  lol_tracker_data: